### ISSUE TITLE
Getting error running dart tasks

### ISSUE THREAD

**Issue by tinabel** [laurenhamel/grunt-dart-sass#1]
Getting the following error running the dart sass task:

```
>> SyntaxError: missing ) after argument list
>>     at exports.runInThisContext (vm.js:53:16)
>>     at Module._compile (module.js:387:25)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:20:19)
>>     at loadTask (/home/vagrant/workspace/accelerator/buildTools/node_modules/grunt/lib/grunt/task.js:323:10)
>>     at /home/vagrant/workspace/accelerator/buildTools/node_modules/grunt/lib/grunt/task.js:361:7
>>     at Array.forEach (native)

```

**Comment by laurenhamel** [comment]
@tinabel, could you provide an example of your implementation? I'm unable to reproduce this error, and your stack trace doesn't give any information leading back to the `dart-sass` grunt task.

**Comment by tinabel** [comment]
Man, I wish I could. I just blew away my development environment and am remaking. I will update further when i'm back online.

**Comment by JTSimmons** [comment]
I have this error too. It is due to the fact that you are using async and promises. This is not supported natively in earlier version of nodejs < V7.6.  You should add this into your package.json so that users get an error when trying to install your package if there is a conflict of node versions.

**Comment by ourcore** [comment]
I'm trying to migrate from Ruby Sass, but I'm getting this error too. I'm using Node.js 6.9.1 via nvm and my project doesn't allow me to upgrade. Is there any fix? Thanks

**Comment by JTSimmons** [comment]
> I'm trying to migrate from Ruby Sass, but I'm getting this error too. I'm using Node.js 6.9.1 via nvm and my project doesn't allow me to upgrade. Is there any fix? Thanks

The solution I found is to use [grunt-sass](https://www.npmjs.com/package/grunt-sass) instead.
