### ISSUE TITLE
Missing error messages

### ISSUE THREAD

**Issue by Juburin** [laurenhamel/grunt-dart-sass#2]
Hi, I noticed that messages from dart sass are not displayed when running the grunt task.
That means a user can't see if there was an error.
In [grunt-contrib-sass](https://github.com/gruntjs/grunt-contrib-sass/) all error messages are displayed.

**Comment by laurenhamel** [comment]
@Juburin, I noticed that errors were not getting thrown also, so let me know if the recent `1.1.0` update to the package fixes this issue for you. At present, however, it looks like there may be an npm registry issue when trying to `npm install` the latest `1.1.1` version that I published this morning. I'm working on getting this issue resolved.

**Comment by laurenhamel** [comment]
Just an update: Looks like any issues with `npm install` have been resolved. You should be able to use the latest version (`1.1.1`), which includes a fix for this issue and has been tested.
